In [1]:
import numpy as np

#创建一个行向量
list_row = np.array([1.0,2.0,3.0])
list_row

array([1., 2., 3.])

In [2]:
#创建一个列向量
list_column = np.array([[1.0],[2.0],[3.0]])
list_column

array([[1.],
       [2.],
       [3.]])

In [3]:
# 创建一个矩阵
matrix = np.array([[1, 2],[1, 2],[1, 2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [4]:
from scipy import sparse
#加载稀疏矩阵

In [5]:
matrix_s = np.array([[0, 0],[0, 1],[3, 0]])
matrix_s

array([[0, 0],
       [0, 1],
       [3, 0]])

In [6]:
#创建一个压缩的稀疏行（Compressed Sparse Row，CSR）矩阵
matrix_sparse = sparse.csr_matrix(matrix_s)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [7]:
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],\
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],\
    [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
matrix_large

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [8]:
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


In [9]:
matrix_large_other = np.array([[5, 6, 0, 0, 0, 0, 0, 0, 0, 0],\
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],\
    [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
matrix_large_other_sparse = sparse.csr_matrix(matrix_large_other)
print(matrix_large_other_sparse)

  (0, 0)	5
  (0, 1)	6
  (1, 1)	1
  (2, 0)	3


In [10]:
#numpy直接索引取值，可以避免循环遍历
matrix1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
matrix1[1,2]

6

In [11]:
matrix1[2:]

array([[7, 8, 9]])

In [12]:
#shape、size 和 ndim 函数
#形状
print(matrix1.shape)
#元素个数：行*列
print(matrix1.size)
#矩阵维度
print(matrix1.ndim)

(3, 3)
9
2


In [13]:
#对所有矩阵元素执行指定操作
#通过自定义函数，或者lambda表达式
#创建一个向量化函数并操作矩阵：
function_one = np.vectorize(lambda x:x**2)
function_one(matrix1)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [14]:
#最值：max，min
np.max(matrix1)

9

In [15]:
np.max(matrix1[:1])

3

In [16]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
matrix1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [18]:
print(np.max(matrix1.T[1:]))

9


In [19]:
matrix2 = np.array([[51, 23, 3],[4, 15, 62],[47, 18, 39]])
matrix2

array([[51, 23,  3],
       [ 4, 15, 62],
       [47, 18, 39]])

In [20]:
#列维度
np.max(matrix2,axis=0)

array([51, 23, 62])

In [21]:
#行维度
np.min(matrix2,axis=1)

array([ 3,  4, 18])

In [22]:
#平均值：mean、方差：var 和 标准差：std
#同样可以使用上面的维度，也可以操作整个ndarray
np.mean(matrix2)

29.11111111111111

In [23]:
np.var(matrix2)

405.65432098765433

In [24]:
np.std(matrix2,axis=0)

array([21.27596453,  3.29983165, 24.28076514])

In [25]:
#矩阵的变形
matrix3 = np.array([[51, 23, 3],[4, 15, 62],[47, 18, 39],[23,25,24]])
matrix3.reshape(2,6)

array([[51, 23,  3,  4, 15, 62],
       [47, 18, 39, 23, 25, 24]])

In [26]:
matrix2.size

9

In [27]:
matrix2.reshape(1,-1)
#等价于flatten

array([[51, 23,  3,  4, 15, 62, 47, 18, 39]])

In [28]:
matrix2.flatten()

array([51, 23,  3,  4, 15, 62, 47, 18, 39])

In [29]:
#矩阵转置
matrix2[2:].T

array([[47],
       [18],
       [39]])

In [30]:
matrix2

array([[51, 23,  3],
       [ 4, 15, 62],
       [47, 18, 39]])

In [31]:
matrix2.T[2:]

array([[ 3, 62, 39]])

In [32]:
#矩阵的秩
matrix4 = np.array([[1, 1, 1],[1, 1, 1],[1, 1, 1]])
np.linalg.matrix_rank(matrix4)
#计算行列式
np.linalg.det(matrix4)
#获取对角元素
print(matrix2)
matrix2.diagonal()

[[51 23  3]
 [ 4 15 62]
 [47 18 39]]


array([51, 15, 39])

In [33]:
#对角线向上偏移
matrix2.diagonal(offset=1)
#对角线向下偏移
matrix2.diagonal(offset=-1)
#矩阵的迹：对角线元素的和：常被用在机器学习方法的底层计算
print(matrix2.trace())
    #同样可用对角线求和：
sum(matrix2.diagonal())

#计算特征值和特征向量

105


105

In [34]:
matrix5 = np.array([[1, -1, 3],[1, 1, 6],[3, 8, 9]])
eigenvalues,eigenvectors = np.linalg.eig(matrix5)
print(eigenvalues)
print(eigenvectors)

[13.55075847  0.74003145 -3.29078992]
[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


In [35]:
#矩阵点积
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
print(np.dot(vector_a,vector_b))
#等价于以下情况：使用@
vector_a@vector_b

32


32

In [36]:
#加减乘除为对应相加相减相乘相除
vector_a/vector_b

array([0.25, 0.4 , 0.5 ])

In [37]:
#矩阵的逆
print(matrix2)
np.linalg.inv(matrix2)

[[51 23  3]
 [ 4 15 62]
 [47 18 39]]


array([[-0.01541185, -0.02446741,  0.04008243],
       [ 0.08004876,  0.05363673, -0.09142625],
       [-0.01837232,  0.00473095,  0.01953329]])

In [38]:
#伪随机数生成
#生成随机数种子
"""
多次返回相同的随机数对于获取可预测、可重复的结果是很有用的。
如果希望多次返回同样的随机数，
可以设置伪随机数生成器的“种子”（一个整数）。
如果在程序中用到了随机数，
则拥有相同“种子”的程序会生成同样的结果。
"""
np.random.seed(0)

In [39]:
#生成3个0.0到1.0之间的随机浮点数
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [40]:
#生成3个0到10之间的随机整数
np.random.randint(0, 11, 3)

array([3, 7, 9])

In [41]:
#从平均值是1.1且标准差是2.0的正态分布中抽取5个数
np.random.normal(1.1, 2.0, 5)

array([-1.74465169,  4.14013898,  0.51721205,  0.83381943,  0.75386081])

In [42]:
#从平均值是0.0且分散程度是1.0的logistics分布中抽取3个数
np.random.logistic(0.0, 1.0, 3)

array([ 1.46416405, -0.08013416, -0.4356214 ])

In [43]:
#从大于或等于11.0并且小于12.0的范围中抽取4个数
np.random.uniform(11.0, 12.0, 4)

array([11.83607876, 11.33739616, 11.64817187, 11.36824154])